[package]
name = "example_app"
version = "0.1.0"
authors = ["Fireboltofdeath"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocheck = {path = "../"}

rouille = "3.0.0"
tokio = "0.2"